---
- name: get spp
  git: repo=http://dpdk.org/git/apps/spp
       dest={{ spp_dir }}

- name: install dpdk in spp
  command: make install T={{ dpdk_target }} chdir={{ spp_dir }}

- name: make spp
  command: make RTE_SDK={{ spp_dir }} RTE_TARGET={{ dpdk_target }} -C examples/multi_process/patch_panel chdir={{ spp_dir }}
